# Generated by Django 2.2.2 on 2021-03-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='just_course',
        ),
        migrations.AlterModelTable(
            name='coursecategory',
            table='just_course_category',
        ),
        migrations.AlterModelTable(
            name='coursesection',
            table='just_course_Section',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='just_teacher',
        ),
    ]
