# Generated by Django 2.2.2 on 2021-03-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210324_1534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursechapter',
            table='just_course_chapter',
        ),
    ]
