# Generated by Django 2.2.2 on 2021-03-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursecategory_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attachment_path',
            field=models.CharField(blank=True, default=None, help_text='若是video，填vid,若是文档，填link', max_length=255, null=True, verbose_name='课程介绍链接'),
        ),
    ]
