# Generated by Django 2.2.2 on 2021-03-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210329_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='课程受欢迎程度'),
        ),
    ]
