# Generated by Django 2.2.2 on 2021-04-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_brief_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('orders', models.IntegerField()),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='总分类名称')),
            ],
            options={
                'verbose_name': '总分类',
                'verbose_name_plural': '总分类',
                'db_table': 'just_general_category',
            },
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='general_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.GeneralCategory', verbose_name='课程分类'),
        ),
    ]
