# Generated by Django 2.2.2 on 2021-04-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20210403_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='button',
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='general_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursecategrories', to='course.GeneralCategory', verbose_name='总目录分类'),
        ),
    ]
