# Generated by Django 2.2.2 on 2021-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210403_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcategory',
            name='show',
            field=models.BooleanField(default=False, verbose_name='前端展示遍历'),
        ),
    ]
