# Generated by Django 2.2.2 on 2021-04-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20210404_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='project',
            field=models.SmallIntegerField(choices=[(0, '仅理论'), (1, '理论实践')], default=1, verbose_name='是否有项目实战课程分类'),
        ),
        migrations.AddField(
            model_name='generalcategory',
            name='project',
            field=models.SmallIntegerField(choices=[(0, '仅理论'), (1, '理论实践')], default=1, verbose_name='是否有项目实战总类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.SmallIntegerField(choices=[(0, '零基础'), (1, '进阶'), (2, '高阶')], default=0, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='project',
            field=models.SmallIntegerField(choices=[(0, '理论'), (1, '项目实战')], default=0, verbose_name='是否为项目实战课程'),
        ),
    ]
