# Generated by Django 2.2.2 on 2021-04-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20210406_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='brief_text',
        ),
    ]
