# Generated by Django 2.2.2 on 2021-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='tencent',
            field=models.IntegerField(default=None),
        ),
    ]
