# Generated by Django 2.2.2 on 2021-03-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210325_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(default='你还没有填简介啊~~', max_length=64),
        ),
    ]
