# Generated by Django 2.2.2 on 2021-03-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210327_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tencent',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
