# Generated by Django 2.2.2 on 2021-03-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_comment_praise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praise',
            name='orders',
        ),
    ]
