# Generated by Django 2.2.2 on 2021-03-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_praise_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='用户评论'),
        ),
    ]
