# Generated by Django 2.2.2 on 2021-03-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210331_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='用户评论'),
        ),
    ]
