# Generated by Django 2.2.2 on 2021-04-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210331_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='orders',
        ),
    ]
