# Generated by Django 2.2.2 on 2021-04-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_comment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_course', to='course.Course', verbose_name='评论的课程'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_user', to='user.User', verbose_name='评论的用户'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='praise_course', to='course.Course', verbose_name='点赞的课程'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='praise_user', to='user.User', verbose_name='点赞用户'),
        ),
    ]
