# Generated by Django 2.2.2 on 2021-03-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='just_order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='just_order_detail',
        ),
    ]
